name: Publish on NPM

on:
  push:
    paths:
      - '.github/workflows/test-and-publish.yml'
      - 'package.json'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install node deps
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Cleanup docker
        if: always()
        run: npm run test:clear
  publish-npm:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 15

      - name: Installing NPM deps
        run: npm install

      - name: Build modules
        run: npm run build

      - name: Publishing on NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}